name: CI

on:
  push:
    branches: [source, ci-test]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 8
          cache: yarn
      - run: yarn
      - run: yarn deploy
